name: introvert
description: Sovereign peer-to-peer mesh network client with integrated $INTR token economy.
version: 0.35.1+1
publish_to: none
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  path: ^1.8.3
  provider: ^6.0.5
  uuid: ^4.3.3
  flutter_callkit_incoming: ^3.0.0
  shared_preferences: ^2.5.5
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  image: ^4.1.0
  path_provider: ^2.1.5
  crypto: ^3.0.3
  open_file: ^3.3.0
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  pdf_render_maintained:
    path: plugins/pdf_render_maintained
  flutter_video_thumbnail_plus: ^1.0.6
  record: ^7.0.0
  audioplayers: ^6.7.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  package_info_plus: ^9.0.1
  video_player: ^2.9.2
  flutter_webrtc: ^0.14.1
  flutter_svg: ^2.0.10
  flutter_secure_storage: ^9.2.4
  flutter_inappwebview: ^6.1.5
  flutter_markdown: ^0.7.7
  share_plus: ^10.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  macos:
    generate: true
  windows:
    generate: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true
  ios_content_mode: "scaleAspectFit"

flutter_native_splash:
  color: "#1E1E1E"
  image: "assets/images/app_icon_swarm_2.png"
  android_12:
    image: "assets/images/app_icon_swarm_2.png"
    color: "#1E1E1E"

flutter:
  config:
    enable-swift-package-manager: false
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_black.png
    - assets/images/logo_white.png
    - assets/images/icon_transparent.png
    - assets/images/default_avatar.png
    - assets/images/app_icon.png
    - assets/images/introvert_wallpaper.png
    - assets/images/stickers/
    - assets/images/kliphy/
    - assets/audio/introvert_ping.m4a
    - assets/images/reply_privately.svg
    - assets/images/theme_beach.jpg
    - assets/images/theme_cybercity.jpg
    - assets/images/theme_forest.jpg
    - assets/images/theme_mountain1.jpg
    - assets/images/theme_mountain2.jpg
    - assets/images/theme_canyon.jpg
    - assets/images/theme_desert.jpg
    - assets/images/theme_winter.jpg
    - assets/images/theme_light1.jpg
    - assets/images/theme_light2.jpg
    - assets/images/theme_light3.jpg
    - assets/images/theme_cyber_city2.jpg
    - assets/images/theme_cyber_city3.jpg
    - assets/images/defaultfanowp.png
    - assets/images/fifa/
    - assets/images/introvert_explained/
